# Generated by Django 3.0.5 on 2021-05-23 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperature',
            old_name='day',
            new_name='Day',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='humidity',
            new_name='Humidity',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='temp',
            new_name='Temperature',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='time',
            new_name='Time',
        ),
    ]
